### ISSUE TITLE
这算问题吗？

### ISSUE THREAD

**Issue by kaioser** [lihuaqigh/UIButton-ImageTitle#1]
![2018-03-01 5 06 17](https://user-images.githubusercontent.com/30762999/36836682-03f398e4-1d75-11e8-8670-b2a33cf2c4d5.png)
![2018-03-01 5 07 58](https://user-images.githubusercontent.com/30762999/36836692-0abea8c6-1d75-11e8-9a14-ae58dc373445.png)
![2018-03-01 5 08 03](https://user-images.githubusercontent.com/30762999/36836697-0d77a932-1d75-11e8-96c0-f88afa9d534f.png)

**Comment by lihuaqigh** [comment]
算是bug。已经加载按钮后，要根据文字变化，动态改变按钮的 frame。所以得重写layout subviews，获取title和image的不同状态下的frame。

**Comment by kaioser** [comment]
那我该怎么修改呢，点击方法里重新layout??

**Comment by lihuaqigh** [comment]
我已经修复了，你可以参考一下代码

**Comment by kaioser** [comment]
好的 好使了刚才试了一下
